/**
 * Lookup table mapping callout text to MD5 hash key (first 10 chars).
 * Keys match filenames generated by scripts/generate-tts.mjs.
 */

const TEXT_TO_KEY = {
  // Ch01
  "First, open the Quick Settings menu by swiping down": "3098c1b478",
  "Now tap Bluetooth to begin pairing your device": "4d0619863b",
  "Your device will appear here once it is discovered": "742134214d",
  "Your Bluetooth device is now connected": "3189ca5f28",
  "Both inputs are now active in Stereo Mode": "57205851f9",
  "Bluetooth is connected and ready to use": "e1bfb78d79",
  // Ch02
  "To begin recording, tap the REC button": "e358791237",
  "The red dot pulses to indicate recording is in progress": "b3c370969a",
  "Recording has stopped. You can now review it before saving": "82d5913aab",
  "Tap play to preview your recording": "5026d16436",
  "Your track has been saved to the file manager": "a592146eac",
  "You can record, review, and save all from the home screen": "6fdad27a95",
  // Ch03
  "Tap any preset button to select a room acoustic": "1c0cb54b57",
  "Studio B is now selected": "5f95939e0d",
  "Tap the info icon to read the acoustic description": "b7752d2251",
  "Great Hall is now selected": "af33a4d7df",
  "Here is the Grand Cathedral preset": "4a99b56de6",
  "There are 9 acoustic presets to transform your space with just one tap": "671fba5714",
  // Ch04
  "Use the right sidebar to control the Active Acoustics volume": "84dc6adc09",
  "Drag the slider up to increase the volume": "bc1ccec247",
  "The volume is now at maximum": "bd3b290709",
  "Drag the slider down to decrease the volume": "f4e4eaf0fa",
  "Tap here to mute or unmute Active Acoustics": "adfb43088f",
  "The volume control is independent of recording and playback levels": "e6237860c9",
  // Ch05
  "Select a track to begin playback": "c2af14fc19",
  "You are now in playback mode. Use the scrubber to seek through the track": "088e988777",
  "You can scrub forward through the track like this": "ad5c1ae284",
  "The progress bar moves in real time as the track plays": "cf472d3a42",
  "Tap the skip button to jump to the next track": "258b5984cf",
  "You can adjust playback volume separately from the acoustics volume": "5d4817f3d2",
  "Full transport controls are available on every screen": "ac0acdd511",
  // Ch06
  "Swipe down from the top of the screen to open Quick Settings": "e91eafe76b",
  "Quick Settings lets you access key controls quickly": "08b20c8f7a",
  "You can toggle Stereo Mode on or off here": "042d2c2688",
  "Or manage your Bluetooth connections here": "a7f1a767ec",
  "You also have quick access to Help, Net Control, Settings, and Standby": "71738bbe72",
  "Quick Settings is always just one swipe away": "1e943e6235",
  // Ch07
  "Stereo Mode processes the left and right channels independently": "3daae67704",
  "Stereo Mode is currently turned off": "275ddf6f74",
  "Stereo Mode is now on with dual-channel processing active": "416a7ac552",
  "Stereo Mode is now off, returning to mono processing": "248719e02d",
  "Please note that Stereo Mode is not available on SoundLok units": "93107d15a2",
  "You can toggle Stereo Mode anytime from Quick Settings": "e0cb04dc95",
  // Ch08
  "You can control Transcend from any device on your Wi-Fi network": "d616ad34bf",
  "Scan this QR code with your phone to open the web interface": "cdde22290b",
  "Make sure your device is on the same Wi-Fi network as Transcend": "aa00e1b5ae",
  "You get full control from any browser with no app needed": "734541a268",
  "Even the standby screen can be accessed remotely": "bb7fedb8c8",
  "With Net Control, you can manage your space from anywhere on the network": "6a8215423a",
  // Ch09
  "You can put Transcend into standby mode to save power": "e667d3d337",
  "Tap confirm to turn off the screen and disable audio": "12d6417e89",
  "The screen is now off and the system is in standby": "8b522ee5e7",
  "Tap the Wake Up button to resume operation": "35e70c36e1",
  "The system has been restored and is ready to use": "b9a1c33dcc",
  "Standby mode saves energy without losing any of your settings": "e5c5295010",
  // Ch10
  "The file manager stores all of your recordings": "5f1ef80153",
  "All of your saved recordings will appear here": "9e980ee334",
  "Track 2 is now selected": "3b6866e97d",
  "Track 2 is now playing": "361ad1d1bf",
  "Long press on a track to access the delete option": "202fa29ae3",
  "The track has been deleted": "3914fdf66f",
  "You can organize all your recordings directly from the controller": "b5972be768",
  // Ch11
  "To access system settings, you will need the admin passcode": "e54416ae9e",
  "Enter the 6-digit admin passcode to continue": "0d6cbe7f5f",
  "Settings are now unlocked and accessible": "f903ca7f9d",
  "From here you can adjust network, audio, and device preferences": "2bd5f592c6",
  "The default admin passcode is 1 2 3 4 5": "46330f95e6",
  // Ch12
  "You can access the full online user guide instantly": "a67415fc19",
  "Scan this code with your phone to open the user guide": "564044c02b",
  "Here you will find links to manuals, videos, and support resources": "8761ef766c",
  "Help is always just one tap away with no manual required": "92bf44a0bd",
};

export function createHash(text) {
  if (TEXT_TO_KEY[text]) return TEXT_TO_KEY[text];
  return null;
}
